=== denispaluca/psemoldyn/src/xml/molsimInput.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <!-- double vector with length 3 -->
  <xsd:complexType name="double_vector">
    <xsd:sequence>
      <xsd:element name="x" type="xsd:string"/>
      <xsd:element name="y" type="xsd:string"/>
      <xsd:element name="z" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

  <!-- integer vector with length 3 -->
  <xsd:complexType name="integer_vector">
    <xsd:sequence>
      <xsd:element name="x" type="xsd:string"/>
      <xsd:element name="y" type="xsd:string"/>
      <xsd:element name="z" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
  
  <!-- specification of one cuboid -->
  <xsd:complexType name="cuboid">
    <xsd:sequence>
      <!-- coordinates of cuboid -->
      <xsd:element name="coordinates" type="double_vector"/>
      <!-- Number of particles per dimension -->
      <xsd:element name="particles_per_dimension" type="integer_vector"/>
      <!-- Mesh width/distance beween particles -->
      <xsd:element name="distance_particles" type="xsd:string"/>
      <!-- mass of one particle -->
      <xsd:element name="mass" type="xsd:string"/>
      <!-- initial velocity -->
      <xsd:element name="velocity" type="double_vector"/>
    </xsd:sequence>
  </xsd:complexType>
  
  <!-- multiple cuboids -->
  <xsd:complexType name="cuboid_cluster">
    <xsd:sequence>
      <xsd:element name="cuboid" type="cuboid" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  
  <!-- specification of one particle -->  
  <xsd:complexType name="particle">
    <xsd:sequence>
      <!-- coordinates of particle -->
      <xsd:element name="coordinates" type="double_vector"/>
      <!-- initial velocity -->
      <xsd:element name="velocity" type="double_vector"/>
      <!-- mass of particle -->
      <xsd:element name="mass" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
  
  <!-- multiple particles -->
  <xsd:complexType name="particle_cluster">
    <xsd:sequence>
      <xsd:element name="particle" type="particle" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  
  <!-- specify how you want to specify the input particles -->
  <xsd:complexType name="input_particles">
    <xsd:choice>
      <!-- .particle file -->
      <xsd:element name="particle_file" type="xsd:string"/>
      <!-- .cuboids file -->
      <xsd:element name="cuboids_file" type="xsd:string"/>
      <!-- Directly specify cuboids -->
      <xsd:element name="cuboids" type="cuboid_cluster"/>
      <!-- Set t_end -->
      <xsd:element name="particles" type="particle_cluster"/>
    </xsd:choice>
  </xsd:complexType>

  <!-- base element of the molsim input xml file -->
  <xsd:complexType name="molsimInput">
    <xsd:sequence>
      <!-- Set base name of output files (optional, default name: MD_vtk) -->
      <xsd:element name="name_output" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <!-- Set frequency of the output files (optional, default: 10) -->
      <xsd:element name="frequency_output" type="xsd:int" minOccurs="0" maxOccurs="1"/>
      <!-- Set delta_t -->
      <xsd:element name="delta_t" type="xsd:double"/>
      <!-- Set t_end -->
      <xsd:element name="t_end" type="xsd:double"/>
      <!-- Set input particles -->
      <xsd:element name="filelocation" type="xsd:string"/>
    </xsd:sequence>    
  </xsd:complexType>


  <xsd:element name="molsimInput" type="molsimInput"/>

</xsd:schema>

=== denispaluca/psemoldyn/src/xml/input-particles.xml
<?xml version="1.0"?>
<molsimInput xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="molsimInput.xsd">
   <!-- <name_output>Name of </name_output> -->
    <!-- <frequency_output>10</frequency_output> -->
    <delta_t>0.01</delta_t>
    <t_end>2</t_end>
    <particles>
        <particles>
            <particle>
                <coordinates>
                    <x>1</x>
                    <y>2</y>
                    <z>3</z>
                </coordinates>
                <velocity>
                    <x>2.1</x>
                    <y>3.1</y>
                    <z>4.1</z>
                </velocity>
                <mass>1.27</mass>
            </particle>
        </particles>
    </particles>
</molsimInput>

=== denispaluca/psemoldyn/src/xml/input-cuboids.xml
<?xml version="1.0"?>
<molsimInput xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="molsimInput.xsd">
   <!-- <name_output>Name of </name_output> -->
    <!-- <frequency_output>10</frequency_output> -->
    <delta_t>0.01</delta_t>
    <t_end>2</t_end>
    <particles>
        <cuboids>
            <cuboid>
                <coordinates>
                    <x>1</x>
                    <y>2</y>
                    <z>3</z>
                </coordinates>
                <particles_per_dimension>
                    <x>4</x>
                    <y>5</y>
                    <z>6</z>
                </particles_per_dimension>
                <distance_particles>0.1</distance_particles>
                <mass>0.5</mass>
                <velocity>
                    <x>1.1</x>
                    <y>2.2</y>
                    <z>3.3</z>
                </velocity>
            </cuboid>
        </cuboids>
    </particles>
</molsimInput>
